### ISSUE TITLE
The Explain feature

### ISSUE THREAD

**Issue by gregn610** [Bubbler-4/piet#5]
Great project, thanks for sharing!

[Explain plan](https://bubbler-4.github.io/piet/#eJzlmM9uhCAQxt-F8xzEf4ivYjw0W5tssm03sT01fffdQUVwcUVFStLwHQyS-HPmGxj9IafP14aUVZUDjYEWkEIMUXeBg0Y4XwBlmjJgkEAubme42p1qqCi3W8tHOYYwYqWwDIYkw_inRHdLJLaZ8wO1zGOI2fFYbDUVpT6iZY8zKPKNNed6Pt2ofHJx4DNkfmtQeeswgFKbCKG3VR2fOP3xxnV_gWW5WSnl58fnCZg1D5gHhKWEK5ho4cY5DA9IqmPmk-YVSU1PgEhPnILu7oZnpufbg0xw7JvL5oGeak9Lkg3V6gZxd7RsoFKhMLi4Ju_mMsZhwOVijN-h3DrI66GUIBg9I58tlehAx2BloMmCKw8Ha6YVPQbJZqFuduz61PA5hlrBNQlN0jfU7oE2Ygl1QHF_YN9tJo6GQd2c-NnE8LeSGAzfpRBVnmFZ5XjJxHG_jkEGI-6PJNEzqGfiA4e8OZDIiezBCBsj0pONNIVOwzWaYkozebW9-XFC48wtm2mWKnEnzrTW1cbZ2Ecvdta7ucwmcKVdXAeqroG0zZWUhAC5nN-7i6Y9kfLt5dI2QM4f1-8vnP69AbVfe3M) for  this [fizzbuzz](https://raw.githubusercontent.com/cheezgi/piet-projects/master/fizzbuzz.png).

From the top left  stepping though is it not 1 (red), push(dark red), noop(white), noop(light blue), dup(light green), noop(white),3(light blue) etc? 

The Explain seems to be missing a [noop](https://imgur.com/a/TdXATNf) after the first white?

**Comment by Bubbler-4** [comment]
Each char shown there denotes the command that is run *between* the two areas. In other words, each char describes the associated "edge" between two dots. (This is how Piet actually works, in case you didn't realize yet.) And each number X denotes the single "push X" command; 1 and push are not separate.

So the start of your program actually works like:

```
red -> dark red : push 1
dark red -> white : noop
white -> light blue : noop
light blue -> light green : dup
light green -> light red : dup
light red -> white : noop
white -> light blue : noop
light blue (3 cells) -> blue : push 3
blue -> dark red : mod
dark red -> green : not
green -> dark purple : DP+
...
```

**Comment by gregn610** [comment]
aah, makes sense now. Thanks!
